### ISSUE TITLE
Basic documentation collection

### ISSUE THREAD

**Issue by KarinTreyer** [brightway-lca/brightway-training#6]

**Comment by katrinamag** [comment]
https://github.com/maximikos/Brightway2_Intro/blob/master/BW2_tutorial.ipynb

**Comment by katrinamag** [comment]
https://github.com/PoutineAndRosti/Brightway-Seminar-2017

**Comment by jhuo2021** [comment]
https://github.com/PoutineAndRosti/Brightway-Seminar-2017/blob/master/Day%201%20AM/2%20-%20BW%20structure%20and%20first%20LCAs.ipynb

**Comment by michaelweinold** [comment]
Online course by Prof. Pauliuk in Freiburg that includes Brightway training: https://www.industrialecology.uni-freiburg.de/teaching.aspx/

**Comment by jhuo2021** [comment]
https://gist.github.com/haasad/06286669789f80c95b091b8ed843c558#file-brightway_intro-ipynb

**Comment by lmeul** [comment]
python basics - book https://greenteapress.com/wp/think-python/

**Comment by KarinTreyer** [comment]
Teaching classes by Massimo Pizzol: https://github.com/massimopizzol/B4B

**Comment by katrinamag** [comment]
https://github.com/brightway-lca/bw_recipe_2016/tree/master/dev

**Comment by KarinTreyer** [comment]
Helpful introductory notebooks by Ben Portner: https://github.com/BenPortner/brightway_recipes

**Comment by lmeul** [comment]
python basics - application examples for all basic operations https://swcarpentry.github.io/python-novice-inflammation/

**Comment by jhuo2021** [comment]
advanced LCA notebooks: https://github.com/massimopizzol/advanced-lca-notebooks

**Comment by lmeul** [comment]
python basic tutorial https://docs.python.org/3/tutorial/introduction.html

**Comment by katrinamag** [comment]
Global Sensitivity Analysis from Nicolas Dumoulin https://github.com/NicolasDumoulin/brightway2-sensitivity/blob/master/GSA.ipynb

**Comment by jhuo2021** [comment]
linking with IAMs: https://github.com/brightway-lca/matrix_utils/blob/ad5d393a667952cfa09dd92113c65a6a5d9dbb27/dev/Brightway%202.5%20-%20Linking%20with%20IAMs.ipynb

**Comment by KarinTreyer** [comment]
https://github.com/maxkoslowski/Brightway2_Intro/blob/master/BW2_tutorial.ipynb A notebook for beginners designed to get you started (creating a project, setting up database(s) and simple foreground systems, performing impact assessments, analysing results, performing Monte Carlo simulations)

**Comment by shuyanxiong** [comment]
Brightway2 input and output https://github.com/brightway-lca/brightway2-io

**Comment by KarinTreyer** [comment]
[LCA_WIND_DK](https://github.com/romainsacchi/LCA_WIND_DK/blob/master/LCA_parameterized_model_Eolien_public.ipynb) very advanced use of brightway to construct "technologically, temporally and geographically-sensitive life cycle inventories" of every wind turbine in Denmark

**Comment by andreadm84** [comment]
LCA ontology
https://github.com/tishchungoora/lca-ontology

**Comment by mkvdhulst** [comment]
Import Exiobase v3 into brightway2 https://github.com/massimopizzol/Exio3-to-bw2

**Comment by shuyanxiong** [comment]
Brightway2 data management https://github.com/brightway-lca/brightway2-data#brightway2-data-management

**Comment by andreadm84** [comment]
a list collecting **awesome** LCA resources
https://github.com/alpby/awesome-lca

**Comment by jhuo2021** [comment]
Premise examples: https://github.com/polca/premise/blob/7cd69ce34c44b9bceb74b41609265dda64ecc576/examples/.ipynb_checkpoints/examples-checkpoint.ipynb

**Comment by lmeul** [comment]
https://pymbook.readthedocs.io/en/latest/index.html python basics

**Comment by KarinTreyer** [comment]
https://github.com/brightway-lca/from-the-ground-up

**Comment by shuyanxiong** [comment]
presamples (scenario analysis and for the reuse of sampled data in Monte Carlo Simulations in the [Brightway LCA framework])   https://github.com/PascalLesage/presamples

**Comment by jhuo2021** [comment]
learning brightway: https://github.com/macmribo/learningbrightway

**Comment by lmeul** [comment]
google python class https://developers.google.com/edu/python/

**Comment by KarinTreyer** [comment]
https://github.com/brightway-lca/from-the-ground-up/tree/main/basic%20tasks

**Comment by mkvdhulst** [comment]
https://github.com/MTES-MCT/ecobalyse-data/blob/9516b81c2e40336b30969fb5bef6d1a3c911434a/brightway/brightway_tutorial_notebooks/BW2_tutorial.ipynb

**Comment by lmeul** [comment]
python books http://codingthematrix.com/ https://www.oreilly.com/library/view/fluent-python/9781491946237/  https://nostarch.com/automatestuff2

**Comment by andreadm84** [comment]
https://github.com/michaelweinold/public_site_lca

**Comment by lmeul** [comment]
databases example cmutel https://github.com/brightway-lca/brightway2/blob/master/notebooks/Databases.ipynb

**Comment by katrinamag** [comment]
How to use the Wurst library: https://github.com/IndEcol/wurst-examples/blob/master/introduction/Introduction%20and%20Wurst%20basics.ipynb

**Comment by jhuo2021** [comment]
seaweed bioplastic lca example: https://github.com/massimopizzol/seaweed-bioplastic-lca/blob/ff085737d5c343aae42be81aa9f78909c1a6a4f9/Code/Seaweed-Bioplastic-LCA.ipynb

**Comment by shuyanxiong** [comment]
Extension to Brightway2 LCA framework to create and work with aggregated data  https://github.com/CIRAIG/brightway2-aggregated

**Comment by mkvdhulst** [comment]
A compilation of code snippets, useful when using brightway2, the python framework for life cycle assessment, especially when starting https://github.com/ntropy-esa/bw2-snippets/blob/0a691195b5b3ef3e3c92efebd0af35b37ca79b17/bw2-snippets.ipynb

**Comment by mkvdhulst** [comment]
https://github.com/rauner/holistic-coal-exit/tree/0daeb4a3ff8a9013a66cb8c79e33e8cc68283e5a

**Comment by KarinTreyer** [comment]
![image](https://user-images.githubusercontent.com/28534018/193029650-97e913a9-1d30-4fde-af5f-079f36cde4eb.png)
From the teaching experience of Massimo Pizzol presented @Brightcon2020. https://2020.brightcon.link/

**Comment by shuyanxiong** [comment]
IO tools for Brightway LCA framework https://github.com/brightway-lca/bw_io

**Comment by andreadm84** [comment]
LCA results visualization

https://github.com/alvarojhahn/LCA-results-visualization---BW2

**Comment by mkvdhulst** [comment]
https://github.com/cmutel/spatial-assessment-blog/tree/6236de3129ef777488337d0e1e7a19a38f6cef39/notebooks

**Comment by mkvdhulst** [comment]
Example parameterised cradle-to-gate life cycle assessment: Linking BatPaC to Brightway https://github.com/jbaars2/Batt_Sust_Model/blob/02bb1862f53266e843497231af65144f57a85e48/example%20notebooks/Battery%20emissions/example_lifecycle_emissions.ipynb

**Comment by jhuo2021** [comment]
soil database by Thomas Sonderegger: https://github.com/ethz-esd/compaction_erosion_sonderegger_2020/blob/e5f906e2bd6b99f1400034e31ea78eb0b18f8fda/python_code/1_soil-database-machinery-fieldwork.ipynb

**Comment by katrinamag** [comment]
Sensitivity analysis w/ linear regression, multivariable linear regression, log regression:  https://github.com/hdlee4u/sensitivity_analysis/blob/master/sensitivity_anaysis.ipynb

**Comment by jhuo2021** [comment]
Wurst: https://github.com/IndEcol/wurst-examples/blob/13622bfa5df6480c9cd5a4e6c95664815877945b/introduction/Introduction%20and%20Wurst%20basics.ipynb

**Comment by shuyanxiong** [comment]
Manager for Brightway LCA libraries and projects https://github.com/brightway-lca/bw_projects

**Comment by michaelweinold** [comment]
The above links are now collected in a table added with https://github.com/brightway-lca/brightway-training/commit/34d2de34f77feecb542f7b8da1440a2fc298f043
